package com.zxsc.springboot.bean;

import java.util.List;

public class GoodsType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.cid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.type
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public String type;
    public List<TypeType> typeTypes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.id
     *
     * @return the value of goodstype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.id
     *
     * @param id the value for goodstype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.cid
     *
     * @return the value of goodstype.cid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.cid
     *
     * @param cid the value for goodstype.cid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.type
     *
     * @return the value of goodstype.type
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.type
     *
     * @param type the value for goodstype.type
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}