package com.zxsc.springboot.bean;

public class TypeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typetype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typetype.gid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typetype.name
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typetype.id
     *
     * @return the value of typetype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typetype.id
     *
     * @param id the value for typetype.id
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typetype.gid
     *
     * @return the value of typetype.gid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typetype.gid
     *
     * @param gid the value for typetype.gid
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typetype.name
     *
     * @return the value of typetype.name
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typetype.name
     *
     * @param name the value for typetype.name
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}