package com.zxsc.springboot.mapper;

import com.zxsc.springboot.bean.ClassificationGoods;
import com.zxsc.springboot.bean.ClassificationGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClassificationGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    long countByExample(ClassificationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int deleteByExample(ClassificationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int insert(ClassificationGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int insertSelective(ClassificationGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    List<ClassificationGoods> selectByExampleWithRowbounds(ClassificationGoodsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    List<ClassificationGoods> selectByExample(ClassificationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    ClassificationGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClassificationGoods record, @Param("example") ClassificationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int updateByExample(@Param("record") ClassificationGoods record, @Param("example") ClassificationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int updateByPrimaryKeySelective(ClassificationGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated Thu Dec 19 11:06:22 CST 2019
     */
    int updateByPrimaryKey(ClassificationGoods record);
}